<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace maiorADV\eBaySDK\PostOrder\Services;

class PostOrderService extends \maiorADV\eBaySDK\PostOrder\Services\PostOrderBaseService
{
    const API_VERSION = 'v2';

    /**
     * @property array $operations Associative array of operations provided by the service.
     */
    protected static $operations = [
        'ApproveCancellationRequest' => [
            'method' => 'POST',
            'resource' => 'cancellation/{cancelId}/approve',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\ApproveCancellationRequestRestResponse',
            'params' => [
                'cancelId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'CheckCancellationEligibility' => [
            'method' => 'POST',
            'resource' => 'cancellation/check_eligibility',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CheckCancellationEligibilityRestResponse',
            'params' => [
            ]
        ],
        'ConfirmCancellationRefund' => [
            'method' => 'POST',
            'resource' => 'cancellation/{cancelId}/confirm',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\ConfirmCancellationRefundRestResponse',
            'params' => [
                'cancelId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetCancellation' => [
            'method' => 'GET',
            'resource' => 'cancellation/{cancelId}?',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetCancellationRestResponse',
            'params' => [
                'cancelId' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'fieldgroups' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'RejectCancellationRequest' => [
            'method' => 'POST',
            'resource' => 'cancellation/{cancelId}/reject',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\RejectCancellationRequestRestResponse',
            'params' => [
                'cancelId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'SearchCancellations' => [
            'method' => 'GET',
            'resource' => 'cancellation/search',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\SearchCancellationsRestResponse',
            'params' => [
                'buyer_login_name' => [
                    'valid' => ['string']
                ],
                'cancel_id' => [
                    'valid' => ['string']
                ],
                'creation_date_range_from' => [
                    'valid' => ['string']
                ],
                'creation_date_range_to' => [
                    'valid' => ['string']
                ],
                'item_id' => [
                    'valid' => ['string']
                ],
                'legacy_order_id' => [
                    'valid' => ['string']
                ],
                'limit' => [
                    'valid' => ['string']
                ],
                'offset' => [
                    'valid' => ['string']
                ],
                'seller_login_name' => [
                    'valid' => ['string']
                ],
                'sort' => [
                    'valid' => ['string']
                ],
                'transaction_id' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'SubmitCancellationRequest' => [
            'method' => 'POST',
            'resource' => 'cancellation',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\SubmitCancellationRequestRestResponse',
            'params' => [
            ]
        ],
        'AppealCaseDecision' => [
            'method' => 'POST',
            'resource' => 'casemanagement/{caseId}/appeal',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\AppealCaseDecisionRestResponse',
            'params' => [
                'caseId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'CloseCase' => [
            'method' => 'POST',
            'resource' => 'casemanagement/{caseId}/close',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CloseCaseRestResponse',
            'params' => [
                'caseId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetCase' => [
            'method' => 'GET',
            'resource' => 'casemanagement/{caseId}',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetCaseRestResponse',
            'params' => [
                'caseId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'IssueCaseRefund' => [
            'method' => 'POST',
            'resource' => 'casemanagement/{caseId}/issue_refund',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\IssueCaseRefundRestResponse',
            'params' => [
                'caseId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'ProvideReturnShipmentInfo' => [
            'method' => 'POST',
            'resource' => 'casemanagement/{caseId}/provide_shipment_info',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\ProvideReturnShipmentInfoRestResponse',
            'params' => [
                'caseId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'ProvidesReturnAddress' => [
            'method' => 'POST',
            'resource' => 'casemanagement/{caseId}/provide_return_address',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\ProvidesReturnAddressRestResponse',
            'params' => [
                'caseId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'SearchCases' => [
            'method' => 'GET',
            'resource' => 'casemanagement/search',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\SearchCasesRestResponse',
            'params' => [
                'case_creation_date_range_from' => [
                    'valid' => ['string']
                ],
                'case_creation_date_range_to' => [
                    'valid' => ['string']
                ],
                'case_status_filter' => [
                    'valid' => ['string']
                ],
                'fieldgroups' => [
                    'valid' => ['string']
                ],
                'item_id' => [
                    'valid' => ['string']
                ],
                'limit' => [
                    'valid' => ['string']
                ],
                'offset' => [
                    'valid' => ['string']
                ],
                'order_id' => [
                    'valid' => ['string']
                ],
                'return_id' => [
                    'valid' => ['string']
                ],
                'sort' => [
                    'valid' => ['string']
                ],
                'transaction_id' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'CheckInquiryEligibility' => [
            'method' => 'POST',
            'resource' => 'inquiry/check_eligibility',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CheckInquiryEligibilityRestResponse',
            'params' => [
            ]
        ],
        'CloseInquiry' => [
            'method' => 'POST',
            'resource' => 'inquiry/{inquiryId}/close',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CloseInquiryRestResponse',
            'params' => [
                'inquiryId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'ConfirmInquiryRefund' => [
            'method' => 'POST',
            'resource' => 'inquiry/{inquiryId}/confirm_refund',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\ConfirmInquiryRefundRestResponse',
            'params' => [
                'inquiryId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'CreateInquiry' => [
            'method' => 'POST',
            'resource' => 'inquiry',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CreateInquiryRestResponse',
            'params' => [
            ]
        ],
        'EscalateInquiry' => [
            'method' => 'POST',
            'resource' => 'inquiry/{inquiryId}/escalate',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\EscalateInquiryRestResponse',
            'params' => [
                'inquiryId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetInquiry' => [
            'method' => 'GET',
            'resource' => 'inquiry/{inquiryId}',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetInquiryRestResponse',
            'params' => [
                'inquiryId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'IssueInquiryRefund' => [
            'method' => 'POST',
            'resource' => 'inquiry/{inquiryId}/issue_refund',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\IssueInquiryRefundRestResponse',
            'params' => [
                'inquiryId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'ProvideInquiryRefundInfo' => [
            'method' => 'POST',
            'resource' => 'inquiry/{inquiryId}/provide_refund_info',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryRefundInfoRestResponse',
            'params' => [
                'inquiryId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'ProvideInquiryShipmentInfo' => [
            'method' => 'POST',
            'resource' => 'inquiry/{inquiryId}/provide_shipment_info',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryShipmentInfoRestResponse',
            'params' => [
                'inquiryId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'SearchInquiries' => [
            'method' => 'GET',
            'resource' => 'inquiry/search',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\SearchInquiriesRestResponse',
            'params' => [
                'fieldgroups' => [
                    'valid' => ['string']
                ],
                'inquiry_creation_date_range_from' => [
                    'valid' => ['string']
                ],
                'inquiry_creation_date_range_to' => [
                    'valid' => ['string']
                ],
                'inquiry_status' => [
                    'valid' => ['string']
                ],
                'item_id' => [
                    'valid' => ['string']
                ],
                'limit' => [
                    'valid' => ['string']
                ],
                'offset' => [
                    'valid' => ['string']
                ],
                'order_id' => [
                    'valid' => ['string']
                ],
                'sort' => [
                    'valid' => ['string']
                ],
                'transaction_id' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'SendInquiryMessage' => [
            'method' => 'POST',
            'resource' => 'inquiry/{inquiryId}/send_message',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\SendInquiryMessageRestResponse',
            'params' => [
                'inquiryId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'AddShippingLabelInfo' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/add_shipping_label',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\AddShippingLabelInfoRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'CancelReturnRequest' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/cancel',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CancelReturnRequestRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'CheckReturnEligibility' => [
            'method' => 'POST',
            'resource' => 'return/check_eligibility',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CheckReturnEligibilityRestResponse',
            'params' => [
            ]
        ],
        'CheckShippingLabelEligibility' => [
            'method' => 'GET',
            'resource' => 'return/{returnId}/check_label_print_eligibility',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CheckShippingLabelEligibilityRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'CreateReturnDraft' => [
            'method' => 'POST',
            'resource' => 'return/draft',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CreateReturnDraftRestResponse',
            'params' => [
            ]
        ],
        'CreateReturnRequest' => [
            'method' => 'POST',
            'resource' => 'return',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CreateReturnRequestRestResponse',
            'params' => [
                'fieldgroups' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'CreateReturnShippingLabel' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/initiate_shipping_label',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CreateReturnShippingLabelRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'DeleteReturnDraftFile' => [
            'method' => 'DELETE',
            'resource' => 'return/draft/{draftId}/file/{fileId}',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\DeleteReturnDraftFileRestResponse',
            'params' => [
                'draftId' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'fileId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'DeleteReturnFile' => [
            'method' => 'DELETE',
            'resource' => 'return/{returnId}/file/{fileId}',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\DeleteReturnFileRestResponse',
            'params' => [
                'fileId' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'EscalateReturn' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/escalate',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\EscalateReturnRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetReturn' => [
            'method' => 'GET',
            'resource' => 'return/{returnId}',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnRestResponse',
            'params' => [
                'fieldgroups' => [
                    'valid' => ['string']
                ],
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetReturnDraft' => [
            'method' => 'GET',
            'resource' => 'return/draft/{draftId}',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftRestResponse',
            'params' => [
                'draftId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetReturnDraftFiles' => [
            'method' => 'GET',
            'resource' => 'return/draft/{draftId}/files',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftFilesRestResponse',
            'params' => [
                'draftId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetReturnEstimate' => [
            'method' => 'POST',
            'resource' => 'return/estimate',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnEstimateRestResponse',
            'params' => [
            ]
        ],
        'GetReturnFiles' => [
            'method' => 'GET',
            'resource' => 'return/{returnId}/files',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnFilesRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetReturnMetadata' => [
            'method' => 'GET',
            'resource' => 'return/metadata/{metadataKey}',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnMetadataRestResponse',
            'params' => [
                'metadataKey' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetReturnPreferences' => [
            'method' => 'GET',
            'resource' => 'return/preference',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnPreferencesRestResponse',
            'params' => [
            ]
        ],
        'GetReturnShippingLabel' => [
            'method' => 'GET',
            'resource' => 'return/{returnId}/get_shipping_label',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnShippingLabelRestResponse',
            'params' => [
                'return_id' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetShipmentTracking' => [
            'method' => 'GET',
            'resource' => 'return/{returnId}/tracking',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetShipmentTrackingRestResponse',
            'params' => [
                'carrier_used' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'tracking_number' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'IssueReturnRefund' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/issue_refund',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\IssueReturnRefundRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'MarkReturnReceived' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/mark_as_received',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\MarkReturnReceivedRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'MarkReturnRefundReceived' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/mark_refund_received',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundReceivedRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'MarkReturnRefundSent' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/mark_refund_sent',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundSentRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'MarkReturnShipped' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/mark_as_shipped',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\MarkReturnShippedRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'ProcessReturnRequest' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/decide',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\ProcessReturnRequestRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'SearchReturns' => [
            'method' => 'GET',
            'resource' => 'return/search',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\SearchReturnsRestResponse',
            'params' => [
                'creation_date_range_from' => [
                    'valid' => ['string']
                ],
                'creation_date_range_to' => [
                    'valid' => ['string']
                ],
                'item_id' => [
                    'valid' => ['string']
                ],
                'limit' => [
                    'valid' => ['string']
                ],
                'offset' => [
                    'valid' => ['string']
                ],
                'return_state' => [
                    'valid' => ['string']
                ],
                'sort' => [
                    'valid' => ['string']
                ],
                'states' => [
                    'valid' => ['string']
                ],
                'transaction_id' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'SendReturnMessage' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/send_message',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\SendReturnMessageRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'SendReturnShippingLabel' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/send_shipping_label',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\SendReturnShippingLabelRestResponse',
            'params' => [
                'return_id' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'to_email_address' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'SetReturnPreferences' => [
            'method' => 'POST',
            'resource' => 'return/preference',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\SetReturnPreferencesRestResponse',
            'params' => [
            ]
        ],
        'SubmitReturnFile' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/file/submit',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\SubmitReturnFileRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'UpdateReturnDraft' => [
            'method' => 'PUT',
            'resource' => 'return/draft/{draftId}',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\UpdateReturnDraftRestResponse',
            'params' => [
                'draftId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'UpdateShipmentTracking' => [
            'method' => 'PUT',
            'resource' => 'return/{returnId}/update_tracking',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\UpdateShipmentTrackingRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'UploadReturnDraftFile' => [
            'method' => 'POST',
            'resource' => 'return/draft/{draftId}/file/upload',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\UploadReturnDraftFileRestResponse',
            'params' => [
                'draftId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'UploadReturnFile' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/file/upload',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\UploadReturnFileRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'VoidShippingLabel' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/void_shipping_label',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\VoidShippingLabelRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'CreateCustomList' => [
            'method' => 'POST',
            'resource' => 'rules/custom_list',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CreateCustomListRestResponse',
            'params' => [
            ]
        ],
        'CreateReturnRules' => [
            'method' => 'POST',
            'resource' => 'rules',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\CreateReturnRulesRestResponse',
            'params' => [
            ]
        ],
        'GetCustomList' => [
            'method' => 'GET',
            'resource' => 'rules/custom_list_detail',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetCustomListRestResponse',
            'params' => [
            ]
        ],
        'GetCustomLists' => [
            'method' => 'GET',
            'resource' => 'rules/custom_list',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetCustomListsRestResponse',
            'params' => [
            ]
        ],
        'GetReturnRuleTemplates' => [
            'method' => 'GET',
            'resource' => 'rules/get_templates',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleTemplatesRestResponse',
            'params' => [
            ]
        ],
        'GetStoreCategories' => [
            'method' => 'GET',
            'resource' => 'rules/get_store_category',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetStoreCategoriesRestResponse',
            'params' => [
            ]
        ],
        'GetReturnRule' => [
            'method' => 'GET',
            'resource' => 'rules/{ruleId}',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleRestResponse',
            'params' => [
                'ruleId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetReturnRuleHistory' => [
            'method' => 'GET',
            'resource' => 'rules/{ruleId}/get_trigger_history',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleHistoryRestResponse',
            'params' => [
                'limit' => [
                    'valid' => ['string']
                ],
                'offset' => [
                    'valid' => ['string']
                ],
                'ruleId' => [
                    'valid' => ['string'],
                    'required' => true
                ],
                'trigger_date_range_from' => [
                    'valid' => ['string']
                ],
                'trigger_date_range_to' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'GetReturnRules' => [
            'method' => 'GET',
            'resource' => 'rules/disposition_rules_list',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\GetReturnRulesRestResponse',
            'params' => [
                'fieldgroups' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'UpdateCustomList' => [
            'method' => 'PUT',
            'resource' => 'rules/custom_list',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\UpdateCustomListRestResponse',
            'params' => [
            ]
        ],
        'UpdateReturnRules' => [
            'method' => 'PUT',
            'resource' => 'rules',
            'responseClass' => '\maiorADV\eBaySDK\PostOrder\Types\UpdateReturnRulesRestResponse',
            'params' => [
            ]
        ]
    ];

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ApproveCancellationRequestRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\ApproveCancellationRequestRestResponse
     */
    public function approveCancellationRequest(\maiorADV\eBaySDK\PostOrder\Types\ApproveCancellationRequestRestRequest $request)
    {
        return $this->approveCancellationRequestAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ApproveCancellationRequestRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function approveCancellationRequestAsync(\maiorADV\eBaySDK\PostOrder\Types\ApproveCancellationRequestRestRequest $request)
    {
        return $this->callOperationAsync('ApproveCancellationRequest', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CheckCancellationEligibilityRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CheckCancellationEligibilityRestResponse
     */
    public function checkCancellationEligibility(\maiorADV\eBaySDK\PostOrder\Types\CheckCancellationEligibilityRestRequest $request)
    {
        return $this->checkCancellationEligibilityAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CheckCancellationEligibilityRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkCancellationEligibilityAsync(\maiorADV\eBaySDK\PostOrder\Types\CheckCancellationEligibilityRestRequest $request)
    {
        return $this->callOperationAsync('CheckCancellationEligibility', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ConfirmCancellationRefundRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\ConfirmCancellationRefundRestResponse
     */
    public function confirmCancellationRefund(\maiorADV\eBaySDK\PostOrder\Types\ConfirmCancellationRefundRestRequest $request)
    {
        return $this->confirmCancellationRefundAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ConfirmCancellationRefundRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function confirmCancellationRefundAsync(\maiorADV\eBaySDK\PostOrder\Types\ConfirmCancellationRefundRestRequest $request)
    {
        return $this->callOperationAsync('ConfirmCancellationRefund', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetCancellationRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetCancellationRestResponse
     */
    public function getCancellation(\maiorADV\eBaySDK\PostOrder\Types\GetCancellationRestRequest $request)
    {
        return $this->getCancellationAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetCancellationRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCancellationAsync(\maiorADV\eBaySDK\PostOrder\Types\GetCancellationRestRequest $request)
    {
        return $this->callOperationAsync('GetCancellation', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\RejectCancellationRequestRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\RejectCancellationRequestRestResponse
     */
    public function rejectCancellationRequest(\maiorADV\eBaySDK\PostOrder\Types\RejectCancellationRequestRestRequest $request)
    {
        return $this->rejectCancellationRequestAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\RejectCancellationRequestRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function rejectCancellationRequestAsync(\maiorADV\eBaySDK\PostOrder\Types\RejectCancellationRequestRestRequest $request)
    {
        return $this->callOperationAsync('RejectCancellationRequest', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SearchCancellationsRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\SearchCancellationsRestResponse
     */
    public function searchCancellations(\maiorADV\eBaySDK\PostOrder\Types\SearchCancellationsRestRequest $request)
    {
        return $this->searchCancellationsAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SearchCancellationsRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchCancellationsAsync(\maiorADV\eBaySDK\PostOrder\Types\SearchCancellationsRestRequest $request)
    {
        return $this->callOperationAsync('SearchCancellations', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SubmitCancellationRequestRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\SubmitCancellationRequestRestResponse
     */
    public function submitCancellationRequest(\maiorADV\eBaySDK\PostOrder\Types\SubmitCancellationRequestRestRequest $request)
    {
        return $this->submitCancellationRequestAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SubmitCancellationRequestRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitCancellationRequestAsync(\maiorADV\eBaySDK\PostOrder\Types\SubmitCancellationRequestRestRequest $request)
    {
        return $this->callOperationAsync('SubmitCancellationRequest', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\AppealCaseDecisionRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\AppealCaseDecisionRestResponse
     */
    public function appealCaseDecision(\maiorADV\eBaySDK\PostOrder\Types\AppealCaseDecisionRestRequest $request)
    {
        return $this->appealCaseDecisionAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\AppealCaseDecisionRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function appealCaseDecisionAsync(\maiorADV\eBaySDK\PostOrder\Types\AppealCaseDecisionRestRequest $request)
    {
        return $this->callOperationAsync('AppealCaseDecision', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CloseCaseRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CloseCaseRestResponse
     */
    public function closeCase(\maiorADV\eBaySDK\PostOrder\Types\CloseCaseRestRequest $request)
    {
        return $this->closeCaseAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CloseCaseRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function closeCaseAsync(\maiorADV\eBaySDK\PostOrder\Types\CloseCaseRestRequest $request)
    {
        return $this->callOperationAsync('CloseCase', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetCaseRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetCaseRestResponse
     */
    public function getCase(\maiorADV\eBaySDK\PostOrder\Types\GetCaseRestRequest $request)
    {
        return $this->getCaseAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetCaseRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCaseAsync(\maiorADV\eBaySDK\PostOrder\Types\GetCaseRestRequest $request)
    {
        return $this->callOperationAsync('GetCase', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\IssueCaseRefundRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\IssueCaseRefundRestResponse
     */
    public function issueCaseRefund(\maiorADV\eBaySDK\PostOrder\Types\IssueCaseRefundRestRequest $request)
    {
        return $this->issueCaseRefundAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\IssueCaseRefundRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function issueCaseRefundAsync(\maiorADV\eBaySDK\PostOrder\Types\IssueCaseRefundRestRequest $request)
    {
        return $this->callOperationAsync('IssueCaseRefund', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ProvideReturnShipmentInfoRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\ProvideReturnShipmentInfoRestResponse
     */
    public function provideReturnShipmentInfo(\maiorADV\eBaySDK\PostOrder\Types\ProvideReturnShipmentInfoRestRequest $request)
    {
        return $this->provideReturnShipmentInfoAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ProvideReturnShipmentInfoRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideReturnShipmentInfoAsync(\maiorADV\eBaySDK\PostOrder\Types\ProvideReturnShipmentInfoRestRequest $request)
    {
        return $this->callOperationAsync('ProvideReturnShipmentInfo', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ProvidesReturnAddressRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\ProvidesReturnAddressRestResponse
     */
    public function providesReturnAddress(\maiorADV\eBaySDK\PostOrder\Types\ProvidesReturnAddressRestRequest $request)
    {
        return $this->providesReturnAddressAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ProvidesReturnAddressRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function providesReturnAddressAsync(\maiorADV\eBaySDK\PostOrder\Types\ProvidesReturnAddressRestRequest $request)
    {
        return $this->callOperationAsync('ProvidesReturnAddress', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SearchCasesRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\SearchCasesRestResponse
     */
    public function searchCases(\maiorADV\eBaySDK\PostOrder\Types\SearchCasesRestRequest $request)
    {
        return $this->searchCasesAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SearchCasesRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchCasesAsync(\maiorADV\eBaySDK\PostOrder\Types\SearchCasesRestRequest $request)
    {
        return $this->callOperationAsync('SearchCases', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CheckInquiryEligibilityRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CheckInquiryEligibilityRestResponse
     */
    public function checkInquiryEligibility(\maiorADV\eBaySDK\PostOrder\Types\CheckInquiryEligibilityRestRequest $request)
    {
        return $this->checkInquiryEligibilityAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CheckInquiryEligibilityRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkInquiryEligibilityAsync(\maiorADV\eBaySDK\PostOrder\Types\CheckInquiryEligibilityRestRequest $request)
    {
        return $this->callOperationAsync('CheckInquiryEligibility', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CloseInquiryRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CloseInquiryRestResponse
     */
    public function closeInquiry(\maiorADV\eBaySDK\PostOrder\Types\CloseInquiryRestRequest $request)
    {
        return $this->closeInquiryAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CloseInquiryRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function closeInquiryAsync(\maiorADV\eBaySDK\PostOrder\Types\CloseInquiryRestRequest $request)
    {
        return $this->callOperationAsync('CloseInquiry', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ConfirmInquiryRefundRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\ConfirmInquiryRefundRestResponse
     */
    public function confirmInquiryRefund(\maiorADV\eBaySDK\PostOrder\Types\ConfirmInquiryRefundRestRequest $request)
    {
        return $this->confirmInquiryRefundAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ConfirmInquiryRefundRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function confirmInquiryRefundAsync(\maiorADV\eBaySDK\PostOrder\Types\ConfirmInquiryRefundRestRequest $request)
    {
        return $this->callOperationAsync('ConfirmInquiryRefund', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateInquiryRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CreateInquiryRestResponse
     */
    public function createInquiry(\maiorADV\eBaySDK\PostOrder\Types\CreateInquiryRestRequest $request)
    {
        return $this->createInquiryAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateInquiryRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createInquiryAsync(\maiorADV\eBaySDK\PostOrder\Types\CreateInquiryRestRequest $request)
    {
        return $this->callOperationAsync('CreateInquiry', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\EscalateInquiryRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\EscalateInquiryRestResponse
     */
    public function escalateInquiry(\maiorADV\eBaySDK\PostOrder\Types\EscalateInquiryRestRequest $request)
    {
        return $this->escalateInquiryAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\EscalateInquiryRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function escalateInquiryAsync(\maiorADV\eBaySDK\PostOrder\Types\EscalateInquiryRestRequest $request)
    {
        return $this->callOperationAsync('EscalateInquiry', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetInquiryRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetInquiryRestResponse
     */
    public function getInquiry(\maiorADV\eBaySDK\PostOrder\Types\GetInquiryRestRequest $request)
    {
        return $this->getInquiryAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetInquiryRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInquiryAsync(\maiorADV\eBaySDK\PostOrder\Types\GetInquiryRestRequest $request)
    {
        return $this->callOperationAsync('GetInquiry', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\IssueInquiryRefundRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\IssueInquiryRefundRestResponse
     */
    public function issueInquiryRefund(\maiorADV\eBaySDK\PostOrder\Types\IssueInquiryRefundRestRequest $request)
    {
        return $this->issueInquiryRefundAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\IssueInquiryRefundRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function issueInquiryRefundAsync(\maiorADV\eBaySDK\PostOrder\Types\IssueInquiryRefundRestRequest $request)
    {
        return $this->callOperationAsync('IssueInquiryRefund', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryRefundInfoRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryRefundInfoRestResponse
     */
    public function provideInquiryRefundInfo(\maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryRefundInfoRestRequest $request)
    {
        return $this->provideInquiryRefundInfoAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryRefundInfoRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideInquiryRefundInfoAsync(\maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryRefundInfoRestRequest $request)
    {
        return $this->callOperationAsync('ProvideInquiryRefundInfo', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryShipmentInfoRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryShipmentInfoRestResponse
     */
    public function provideInquiryShipmentInfo(\maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryShipmentInfoRestRequest $request)
    {
        return $this->provideInquiryShipmentInfoAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryShipmentInfoRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideInquiryShipmentInfoAsync(\maiorADV\eBaySDK\PostOrder\Types\ProvideInquiryShipmentInfoRestRequest $request)
    {
        return $this->callOperationAsync('ProvideInquiryShipmentInfo', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SearchInquiriesRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\SearchInquiriesRestResponse
     */
    public function searchInquiries(\maiorADV\eBaySDK\PostOrder\Types\SearchInquiriesRestRequest $request)
    {
        return $this->searchInquiriesAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SearchInquiriesRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchInquiriesAsync(\maiorADV\eBaySDK\PostOrder\Types\SearchInquiriesRestRequest $request)
    {
        return $this->callOperationAsync('SearchInquiries', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SendInquiryMessageRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\SendInquiryMessageRestResponse
     */
    public function sendInquiryMessage(\maiorADV\eBaySDK\PostOrder\Types\SendInquiryMessageRestRequest $request)
    {
        return $this->sendInquiryMessageAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SendInquiryMessageRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendInquiryMessageAsync(\maiorADV\eBaySDK\PostOrder\Types\SendInquiryMessageRestRequest $request)
    {
        return $this->callOperationAsync('SendInquiryMessage', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\AddShippingLabelInfoRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\AddShippingLabelInfoRestResponse
     */
    public function addShippingLabelInfo(\maiorADV\eBaySDK\PostOrder\Types\AddShippingLabelInfoRestRequest $request)
    {
        return $this->addShippingLabelInfoAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\AddShippingLabelInfoRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addShippingLabelInfoAsync(\maiorADV\eBaySDK\PostOrder\Types\AddShippingLabelInfoRestRequest $request)
    {
        return $this->callOperationAsync('AddShippingLabelInfo', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CancelReturnRequestRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CancelReturnRequestRestResponse
     */
    public function cancelReturnRequest(\maiorADV\eBaySDK\PostOrder\Types\CancelReturnRequestRestRequest $request)
    {
        return $this->cancelReturnRequestAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CancelReturnRequestRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelReturnRequestAsync(\maiorADV\eBaySDK\PostOrder\Types\CancelReturnRequestRestRequest $request)
    {
        return $this->callOperationAsync('CancelReturnRequest', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CheckReturnEligibilityRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CheckReturnEligibilityRestResponse
     */
    public function checkReturnEligibility(\maiorADV\eBaySDK\PostOrder\Types\CheckReturnEligibilityRestRequest $request)
    {
        return $this->checkReturnEligibilityAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CheckReturnEligibilityRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkReturnEligibilityAsync(\maiorADV\eBaySDK\PostOrder\Types\CheckReturnEligibilityRestRequest $request)
    {
        return $this->callOperationAsync('CheckReturnEligibility', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CheckShippingLabelEligibilityRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CheckShippingLabelEligibilityRestResponse
     */
    public function checkShippingLabelEligibility(\maiorADV\eBaySDK\PostOrder\Types\CheckShippingLabelEligibilityRestRequest $request)
    {
        return $this->checkShippingLabelEligibilityAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CheckShippingLabelEligibilityRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkShippingLabelEligibilityAsync(\maiorADV\eBaySDK\PostOrder\Types\CheckShippingLabelEligibilityRestRequest $request)
    {
        return $this->callOperationAsync('CheckShippingLabelEligibility', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateReturnDraftRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CreateReturnDraftRestResponse
     */
    public function createReturnDraft(\maiorADV\eBaySDK\PostOrder\Types\CreateReturnDraftRestRequest $request)
    {
        return $this->createReturnDraftAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateReturnDraftRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createReturnDraftAsync(\maiorADV\eBaySDK\PostOrder\Types\CreateReturnDraftRestRequest $request)
    {
        return $this->callOperationAsync('CreateReturnDraft', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateReturnRequestRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CreateReturnRequestRestResponse
     */
    public function createReturnRequest(\maiorADV\eBaySDK\PostOrder\Types\CreateReturnRequestRestRequest $request)
    {
        return $this->createReturnRequestAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateReturnRequestRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createReturnRequestAsync(\maiorADV\eBaySDK\PostOrder\Types\CreateReturnRequestRestRequest $request)
    {
        return $this->callOperationAsync('CreateReturnRequest', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateReturnShippingLabelRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CreateReturnShippingLabelRestResponse
     */
    public function createReturnShippingLabel(\maiorADV\eBaySDK\PostOrder\Types\CreateReturnShippingLabelRestRequest $request)
    {
        return $this->createReturnShippingLabelAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateReturnShippingLabelRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createReturnShippingLabelAsync(\maiorADV\eBaySDK\PostOrder\Types\CreateReturnShippingLabelRestRequest $request)
    {
        return $this->callOperationAsync('CreateReturnShippingLabel', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\DeleteReturnDraftFileRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\DeleteReturnDraftFileRestResponse
     */
    public function deleteReturnDraftFile(\maiorADV\eBaySDK\PostOrder\Types\DeleteReturnDraftFileRestRequest $request)
    {
        return $this->deleteReturnDraftFileAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\DeleteReturnDraftFileRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteReturnDraftFileAsync(\maiorADV\eBaySDK\PostOrder\Types\DeleteReturnDraftFileRestRequest $request)
    {
        return $this->callOperationAsync('DeleteReturnDraftFile', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\DeleteReturnFileRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\DeleteReturnFileRestResponse
     */
    public function deleteReturnFile(\maiorADV\eBaySDK\PostOrder\Types\DeleteReturnFileRestRequest $request)
    {
        return $this->deleteReturnFileAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\DeleteReturnFileRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteReturnFileAsync(\maiorADV\eBaySDK\PostOrder\Types\DeleteReturnFileRestRequest $request)
    {
        return $this->callOperationAsync('DeleteReturnFile', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\EscalateReturnRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\EscalateReturnRestResponse
     */
    public function escalateReturn(\maiorADV\eBaySDK\PostOrder\Types\EscalateReturnRestRequest $request)
    {
        return $this->escalateReturnAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\EscalateReturnRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function escalateReturnAsync(\maiorADV\eBaySDK\PostOrder\Types\EscalateReturnRestRequest $request)
    {
        return $this->callOperationAsync('EscalateReturn', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnRestResponse
     */
    public function getReturn(\maiorADV\eBaySDK\PostOrder\Types\GetReturnRestRequest $request)
    {
        return $this->getReturnAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnAsync(\maiorADV\eBaySDK\PostOrder\Types\GetReturnRestRequest $request)
    {
        return $this->callOperationAsync('GetReturn', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftRestResponse
     */
    public function getReturnDraft(\maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftRestRequest $request)
    {
        return $this->getReturnDraftAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnDraftAsync(\maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftRestRequest $request)
    {
        return $this->callOperationAsync('GetReturnDraft', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftFilesRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftFilesRestResponse
     */
    public function getReturnDraftFiles(\maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftFilesRestRequest $request)
    {
        return $this->getReturnDraftFilesAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftFilesRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnDraftFilesAsync(\maiorADV\eBaySDK\PostOrder\Types\GetReturnDraftFilesRestRequest $request)
    {
        return $this->callOperationAsync('GetReturnDraftFiles', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnEstimateRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnEstimateRestResponse
     */
    public function getReturnEstimate(\maiorADV\eBaySDK\PostOrder\Types\GetReturnEstimateRestRequest $request)
    {
        return $this->getReturnEstimateAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnEstimateRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnEstimateAsync(\maiorADV\eBaySDK\PostOrder\Types\GetReturnEstimateRestRequest $request)
    {
        return $this->callOperationAsync('GetReturnEstimate', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnFilesRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnFilesRestResponse
     */
    public function getReturnFiles(\maiorADV\eBaySDK\PostOrder\Types\GetReturnFilesRestRequest $request)
    {
        return $this->getReturnFilesAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnFilesRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnFilesAsync(\maiorADV\eBaySDK\PostOrder\Types\GetReturnFilesRestRequest $request)
    {
        return $this->callOperationAsync('GetReturnFiles', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnMetadataRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnMetadataRestResponse
     */
    public function getReturnMetadata(\maiorADV\eBaySDK\PostOrder\Types\GetReturnMetadataRestRequest $request)
    {
        return $this->getReturnMetadataAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnMetadataRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnMetadataAsync(\maiorADV\eBaySDK\PostOrder\Types\GetReturnMetadataRestRequest $request)
    {
        return $this->callOperationAsync('GetReturnMetadata', $request);
    }

    /**
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnPreferencesRestResponse
     */
    public function getReturnPreferences()
    {
        return $this->getReturnPreferencesAsync()->wait();
    }

    /**
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnPreferencesAsync()
    {
        return $this->callOperationAsync('GetReturnPreferences');
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnShippingLabelRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnShippingLabelRestResponse
     */
    public function getReturnShippingLabel(\maiorADV\eBaySDK\PostOrder\Types\GetReturnShippingLabelRestRequest $request)
    {
        return $this->getReturnShippingLabelAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnShippingLabelRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnShippingLabelAsync(\maiorADV\eBaySDK\PostOrder\Types\GetReturnShippingLabelRestRequest $request)
    {
        return $this->callOperationAsync('GetReturnShippingLabel', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetShipmentTrackingRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetShipmentTrackingRestResponse
     */
    public function getShipmentTracking(\maiorADV\eBaySDK\PostOrder\Types\GetShipmentTrackingRestRequest $request)
    {
        return $this->getShipmentTrackingAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetShipmentTrackingRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShipmentTrackingAsync(\maiorADV\eBaySDK\PostOrder\Types\GetShipmentTrackingRestRequest $request)
    {
        return $this->callOperationAsync('GetShipmentTracking', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\IssueReturnRefundRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\IssueReturnRefundRestResponse
     */
    public function issueReturnRefund(\maiorADV\eBaySDK\PostOrder\Types\IssueReturnRefundRestRequest $request)
    {
        return $this->issueReturnRefundAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\IssueReturnRefundRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function issueReturnRefundAsync(\maiorADV\eBaySDK\PostOrder\Types\IssueReturnRefundRestRequest $request)
    {
        return $this->callOperationAsync('IssueReturnRefund', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\MarkReturnReceivedRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\MarkReturnReceivedRestResponse
     */
    public function markReturnReceived(\maiorADV\eBaySDK\PostOrder\Types\MarkReturnReceivedRestRequest $request)
    {
        return $this->markReturnReceivedAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\MarkReturnReceivedRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function markReturnReceivedAsync(\maiorADV\eBaySDK\PostOrder\Types\MarkReturnReceivedRestRequest $request)
    {
        return $this->callOperationAsync('MarkReturnReceived', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundReceivedRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundReceivedRestResponse
     */
    public function markReturnRefundReceived(\maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundReceivedRestRequest $request)
    {
        return $this->markReturnRefundReceivedAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundReceivedRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function markReturnRefundReceivedAsync(\maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundReceivedRestRequest $request)
    {
        return $this->callOperationAsync('MarkReturnRefundReceived', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundSentRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundSentRestResponse
     */
    public function markReturnRefundSent(\maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundSentRestRequest $request)
    {
        return $this->markReturnRefundSentAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundSentRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function markReturnRefundSentAsync(\maiorADV\eBaySDK\PostOrder\Types\MarkReturnRefundSentRestRequest $request)
    {
        return $this->callOperationAsync('MarkReturnRefundSent', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\MarkReturnShippedRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\MarkReturnShippedRestResponse
     */
    public function markReturnShipped(\maiorADV\eBaySDK\PostOrder\Types\MarkReturnShippedRestRequest $request)
    {
        return $this->markReturnShippedAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\MarkReturnShippedRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function markReturnShippedAsync(\maiorADV\eBaySDK\PostOrder\Types\MarkReturnShippedRestRequest $request)
    {
        return $this->callOperationAsync('MarkReturnShipped', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ProcessReturnRequestRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\ProcessReturnRequestRestResponse
     */
    public function processReturnRequest(\maiorADV\eBaySDK\PostOrder\Types\ProcessReturnRequestRestRequest $request)
    {
        return $this->processReturnRequestAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\ProcessReturnRequestRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function processReturnRequestAsync(\maiorADV\eBaySDK\PostOrder\Types\ProcessReturnRequestRestRequest $request)
    {
        return $this->callOperationAsync('ProcessReturnRequest', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SearchReturnsRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\SearchReturnsRestResponse
     */
    public function searchReturns(\maiorADV\eBaySDK\PostOrder\Types\SearchReturnsRestRequest $request)
    {
        return $this->searchReturnsAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SearchReturnsRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchReturnsAsync(\maiorADV\eBaySDK\PostOrder\Types\SearchReturnsRestRequest $request)
    {
        return $this->callOperationAsync('SearchReturns', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SendReturnMessageRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\SendReturnMessageRestResponse
     */
    public function sendReturnMessage(\maiorADV\eBaySDK\PostOrder\Types\SendReturnMessageRestRequest $request)
    {
        return $this->sendReturnMessageAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SendReturnMessageRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendReturnMessageAsync(\maiorADV\eBaySDK\PostOrder\Types\SendReturnMessageRestRequest $request)
    {
        return $this->callOperationAsync('SendReturnMessage', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SendReturnShippingLabelRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\SendReturnShippingLabelRestResponse
     */
    public function sendReturnShippingLabel(\maiorADV\eBaySDK\PostOrder\Types\SendReturnShippingLabelRestRequest $request)
    {
        return $this->sendReturnShippingLabelAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SendReturnShippingLabelRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendReturnShippingLabelAsync(\maiorADV\eBaySDK\PostOrder\Types\SendReturnShippingLabelRestRequest $request)
    {
        return $this->callOperationAsync('SendReturnShippingLabel', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SetReturnPreferencesRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\SetReturnPreferencesRestResponse
     */
    public function setReturnPreferences(\maiorADV\eBaySDK\PostOrder\Types\SetReturnPreferencesRestRequest $request)
    {
        return $this->setReturnPreferencesAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SetReturnPreferencesRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setReturnPreferencesAsync(\maiorADV\eBaySDK\PostOrder\Types\SetReturnPreferencesRestRequest $request)
    {
        return $this->callOperationAsync('SetReturnPreferences', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SubmitReturnFileRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\SubmitReturnFileRestResponse
     */
    public function submitReturnFile(\maiorADV\eBaySDK\PostOrder\Types\SubmitReturnFileRestRequest $request)
    {
        return $this->submitReturnFileAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\SubmitReturnFileRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitReturnFileAsync(\maiorADV\eBaySDK\PostOrder\Types\SubmitReturnFileRestRequest $request)
    {
        return $this->callOperationAsync('SubmitReturnFile', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UpdateReturnDraftRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\UpdateReturnDraftRestResponse
     */
    public function updateReturnDraft(\maiorADV\eBaySDK\PostOrder\Types\UpdateReturnDraftRestRequest $request)
    {
        return $this->updateReturnDraftAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UpdateReturnDraftRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateReturnDraftAsync(\maiorADV\eBaySDK\PostOrder\Types\UpdateReturnDraftRestRequest $request)
    {
        return $this->callOperationAsync('UpdateReturnDraft', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UpdateShipmentTrackingRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\UpdateShipmentTrackingRestResponse
     */
    public function updateShipmentTracking(\maiorADV\eBaySDK\PostOrder\Types\UpdateShipmentTrackingRestRequest $request)
    {
        return $this->updateShipmentTrackingAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UpdateShipmentTrackingRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateShipmentTrackingAsync(\maiorADV\eBaySDK\PostOrder\Types\UpdateShipmentTrackingRestRequest $request)
    {
        return $this->callOperationAsync('UpdateShipmentTracking', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UploadReturnDraftFileRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\UploadReturnDraftFileRestResponse
     */
    public function uploadReturnDraftFile(\maiorADV\eBaySDK\PostOrder\Types\UploadReturnDraftFileRestRequest $request)
    {
        return $this->uploadReturnDraftFileAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UploadReturnDraftFileRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadReturnDraftFileAsync(\maiorADV\eBaySDK\PostOrder\Types\UploadReturnDraftFileRestRequest $request)
    {
        return $this->callOperationAsync('UploadReturnDraftFile', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UploadReturnFileRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\UploadReturnFileRestResponse
     */
    public function uploadReturnFile(\maiorADV\eBaySDK\PostOrder\Types\UploadReturnFileRestRequest $request)
    {
        return $this->uploadReturnFileAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UploadReturnFileRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadReturnFileAsync(\maiorADV\eBaySDK\PostOrder\Types\UploadReturnFileRestRequest $request)
    {
        return $this->callOperationAsync('UploadReturnFile', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\VoidShippingLabelRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\VoidShippingLabelRestResponse
     */
    public function voidShippingLabel(\maiorADV\eBaySDK\PostOrder\Types\VoidShippingLabelRestRequest $request)
    {
        return $this->voidShippingLabelAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\VoidShippingLabelRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function voidShippingLabelAsync(\maiorADV\eBaySDK\PostOrder\Types\VoidShippingLabelRestRequest $request)
    {
        return $this->callOperationAsync('VoidShippingLabel', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateCustomListRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CreateCustomListRestResponse
     */
    public function createCustomList(\maiorADV\eBaySDK\PostOrder\Types\CreateCustomListRestRequest $request)
    {
        return $this->createCustomListAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateCustomListRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createCustomListAsync(\maiorADV\eBaySDK\PostOrder\Types\CreateCustomListRestRequest $request)
    {
        return $this->callOperationAsync('CreateCustomList', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateReturnRulesRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\CreateReturnRulesRestResponse
     */
    public function createReturnRules(\maiorADV\eBaySDK\PostOrder\Types\CreateReturnRulesRestRequest $request)
    {
        return $this->createReturnRulesAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\CreateReturnRulesRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createReturnRulesAsync(\maiorADV\eBaySDK\PostOrder\Types\CreateReturnRulesRestRequest $request)
    {
        return $this->callOperationAsync('CreateReturnRules', $request);
    }

    /**
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetCustomListRestResponse
     */
    public function getCustomList()
    {
        return $this->getCustomListAsync()->wait();
    }

    /**
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCustomListAsync()
    {
        return $this->callOperationAsync('GetCustomList');
    }

    /**
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetCustomListsRestResponse
     */
    public function getCustomLists()
    {
        return $this->getCustomListsAsync()->wait();
    }

    /**
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCustomListsAsync()
    {
        return $this->callOperationAsync('GetCustomLists');
    }

    /**
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleTemplatesRestResponse
     */
    public function getReturnRuleTemplates()
    {
        return $this->getReturnRuleTemplatesAsync()->wait();
    }

    /**
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnRuleTemplatesAsync()
    {
        return $this->callOperationAsync('GetReturnRuleTemplates');
    }

    /**
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetStoreCategoriesRestResponse
     */
    public function getStoreCategories()
    {
        return $this->getStoreCategoriesAsync()->wait();
    }

    /**
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStoreCategoriesAsync()
    {
        return $this->callOperationAsync('GetStoreCategories');
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleRestResponse
     */
    public function getReturnRule(\maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleRestRequest $request)
    {
        return $this->getReturnRuleAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnRuleAsync(\maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleRestRequest $request)
    {
        return $this->callOperationAsync('GetReturnRule', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleHistoryRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleHistoryRestResponse
     */
    public function getReturnRuleHistory(\maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleHistoryRestRequest $request)
    {
        return $this->getReturnRuleHistoryAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleHistoryRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnRuleHistoryAsync(\maiorADV\eBaySDK\PostOrder\Types\GetReturnRuleHistoryRestRequest $request)
    {
        return $this->callOperationAsync('GetReturnRuleHistory', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnRulesRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\GetReturnRulesRestResponse
     */
    public function getReturnRules(\maiorADV\eBaySDK\PostOrder\Types\GetReturnRulesRestRequest $request)
    {
        return $this->getReturnRulesAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\GetReturnRulesRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnRulesAsync(\maiorADV\eBaySDK\PostOrder\Types\GetReturnRulesRestRequest $request)
    {
        return $this->callOperationAsync('GetReturnRules', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UpdateCustomListRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\UpdateCustomListRestResponse
     */
    public function updateCustomList(\maiorADV\eBaySDK\PostOrder\Types\UpdateCustomListRestRequest $request)
    {
        return $this->updateCustomListAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UpdateCustomListRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateCustomListAsync(\maiorADV\eBaySDK\PostOrder\Types\UpdateCustomListRestRequest $request)
    {
        return $this->callOperationAsync('UpdateCustomList', $request);
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UpdateReturnRulesRestRequest $request
     * @return \maiorADV\eBaySDK\PostOrder\Types\UpdateReturnRulesRestResponse
     */
    public function updateReturnRules(\maiorADV\eBaySDK\PostOrder\Types\UpdateReturnRulesRestRequest $request)
    {
        return $this->updateReturnRulesAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\PostOrder\Types\UpdateReturnRulesRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateReturnRulesAsync(\maiorADV\eBaySDK\PostOrder\Types\UpdateReturnRulesRestRequest $request)
    {
        return $this->callOperationAsync('UpdateReturnRules', $request);
    }
}
