<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace maiorADV\eBaySDK\Test\Marketing\Types;

use maiorADV\eBaySDK\Marketing\Types\CreateItemPromotionRestResponse;

class CreateItemPromotionRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new CreateItemPromotionRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Marketing\Types\CreateItemPromotionRestResponse', $this->obj);
    }

    public function testExtendsBaseResponse()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Marketing\Types\BaseResponse', $this->obj);
    }
}
