<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace maiorADV\eBaySDK\Finding\Services;

class FindingService extends \maiorADV\eBaySDK\Finding\Services\FindingBaseService
{
    const API_VERSION = '1.13.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationRequest $request
     * @return \maiorADV\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationResponse
     */
    public function getSearchKeywordsRecommendation(\maiorADV\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationRequest $request)
    {
        return $this->getSearchKeywordsRecommendationAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSearchKeywordsRecommendationAsync(\maiorADV\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationRequest $request)
    {
        return $this->callOperationAsync(
            'getSearchKeywordsRecommendation',
            $request,
            '\maiorADV\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationResponse'
        );
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsByKeywordsRequest $request
     * @return \maiorADV\eBaySDK\Finding\Types\FindItemsByKeywordsResponse
     */
    public function findItemsByKeywords(\maiorADV\eBaySDK\Finding\Types\FindItemsByKeywordsRequest $request)
    {
        return $this->findItemsByKeywordsAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsByKeywordsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsByKeywordsAsync(\maiorADV\eBaySDK\Finding\Types\FindItemsByKeywordsRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsByKeywords',
            $request,
            '\maiorADV\eBaySDK\Finding\Types\FindItemsByKeywordsResponse'
        );
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsByCategoryRequest $request
     * @return \maiorADV\eBaySDK\Finding\Types\FindItemsByCategoryResponse
     */
    public function findItemsByCategory(\maiorADV\eBaySDK\Finding\Types\FindItemsByCategoryRequest $request)
    {
        return $this->findItemsByCategoryAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsByCategoryRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsByCategoryAsync(\maiorADV\eBaySDK\Finding\Types\FindItemsByCategoryRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsByCategory',
            $request,
            '\maiorADV\eBaySDK\Finding\Types\FindItemsByCategoryResponse'
        );
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsAdvancedRequest $request
     * @return \maiorADV\eBaySDK\Finding\Types\FindItemsAdvancedResponse
     */
    public function findItemsAdvanced(\maiorADV\eBaySDK\Finding\Types\FindItemsAdvancedRequest $request)
    {
        return $this->findItemsAdvancedAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsAdvancedRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsAdvancedAsync(\maiorADV\eBaySDK\Finding\Types\FindItemsAdvancedRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsAdvanced',
            $request,
            '\maiorADV\eBaySDK\Finding\Types\FindItemsAdvancedResponse'
        );
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsByProductRequest $request
     * @return \maiorADV\eBaySDK\Finding\Types\FindItemsByProductResponse
     */
    public function findItemsByProduct(\maiorADV\eBaySDK\Finding\Types\FindItemsByProductRequest $request)
    {
        return $this->findItemsByProductAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsByProductRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsByProductAsync(\maiorADV\eBaySDK\Finding\Types\FindItemsByProductRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsByProduct',
            $request,
            '\maiorADV\eBaySDK\Finding\Types\FindItemsByProductResponse'
        );
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsIneBayStoresRequest $request
     * @return \maiorADV\eBaySDK\Finding\Types\FindItemsIneBayStoresResponse
     */
    public function findItemsIneBayStores(\maiorADV\eBaySDK\Finding\Types\FindItemsIneBayStoresRequest $request)
    {
        return $this->findItemsIneBayStoresAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsIneBayStoresRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsIneBayStoresAsync(\maiorADV\eBaySDK\Finding\Types\FindItemsIneBayStoresRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsIneBayStores',
            $request,
            '\maiorADV\eBaySDK\Finding\Types\FindItemsIneBayStoresResponse'
        );
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsByImageRequest $request
     * @return \maiorADV\eBaySDK\Finding\Types\FindItemsByImageResponse
     */
    public function findItemsByImage(\maiorADV\eBaySDK\Finding\Types\FindItemsByImageRequest $request)
    {
        return $this->findItemsByImageAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsByImageRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsByImageAsync(\maiorADV\eBaySDK\Finding\Types\FindItemsByImageRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsByImage',
            $request,
            '\maiorADV\eBaySDK\Finding\Types\FindItemsByImageResponse'
        );
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\GetHistogramsRequest $request
     * @return \maiorADV\eBaySDK\Finding\Types\GetHistogramsResponse
     */
    public function getHistograms(\maiorADV\eBaySDK\Finding\Types\GetHistogramsRequest $request)
    {
        return $this->getHistogramsAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\GetHistogramsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHistogramsAsync(\maiorADV\eBaySDK\Finding\Types\GetHistogramsRequest $request)
    {
        return $this->callOperationAsync(
            'getHistograms',
            $request,
            '\maiorADV\eBaySDK\Finding\Types\GetHistogramsResponse'
        );
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\GetVersionRequest $request
     * @return \maiorADV\eBaySDK\Finding\Types\GetVersionResponse
     */
    public function getVersion(\maiorADV\eBaySDK\Finding\Types\GetVersionRequest $request)
    {
        return $this->getVersionAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\GetVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVersionAsync(\maiorADV\eBaySDK\Finding\Types\GetVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getVersion',
            $request,
            '\maiorADV\eBaySDK\Finding\Types\GetVersionResponse'
        );
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsForFavoriteSearchRequest $request
     * @return \maiorADV\eBaySDK\Finding\Types\FindItemsForFavoriteSearchResponse
     */
    public function findItemsForFavoriteSearch(\maiorADV\eBaySDK\Finding\Types\FindItemsForFavoriteSearchRequest $request)
    {
        return $this->findItemsForFavoriteSearchAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindItemsForFavoriteSearchRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsForFavoriteSearchAsync(\maiorADV\eBaySDK\Finding\Types\FindItemsForFavoriteSearchRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsForFavoriteSearch',
            $request,
            '\maiorADV\eBaySDK\Finding\Types\FindItemsForFavoriteSearchResponse'
        );
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindCompletedItemsRequest $request
     * @return \maiorADV\eBaySDK\Finding\Types\FindCompletedItemsResponse
     */
    public function findCompletedItems(\maiorADV\eBaySDK\Finding\Types\FindCompletedItemsRequest $request)
    {
        return $this->findCompletedItemsAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\Finding\Types\FindCompletedItemsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findCompletedItemsAsync(\maiorADV\eBaySDK\Finding\Types\FindCompletedItemsRequest $request)
    {
        return $this->callOperationAsync(
            'findCompletedItems',
            $request,
            '\maiorADV\eBaySDK\Finding\Types\FindCompletedItemsResponse'
        );
    }
}
