<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace maiorADV\eBaySDK\Test\Feedback\Types;

use maiorADV\eBaySDK\Feedback\Types\CreateDSRSummaryByPeriodRequest;

class CreateDSRSummaryByPeriodRequestTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new CreateDSRSummaryByPeriodRequest();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Feedback\Types\CreateDSRSummaryByPeriodRequest', $this->obj);
    }

    public function testExtendsBaseServiceRequest()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Feedback\Types\BaseServiceRequest', $this->obj);
    }
}
