<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace maiorADV\eBaySDK\Test\Metadata\Types;

use maiorADV\eBaySDK\Metadata\Types\GetPoliciesForItemConditionRestResponse;

class GetPoliciesForItemConditionRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetPoliciesForItemConditionRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Metadata\Types\GetPoliciesForItemConditionRestResponse', $this->obj);
    }

    public function testExtendsItemConditionPolicyResponse()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Metadata\Types\ItemConditionPolicyResponse', $this->obj);
    }
}
