<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace maiorADV\eBaySDK\Test\Inventory\Types;

use maiorADV\eBaySDK\Inventory\Types\GetInventoryLocationsRestResponse;

class GetInventoryLocationsRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetInventoryLocationsRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Inventory\Types\GetInventoryLocationsRestResponse', $this->obj);
    }

    public function testExtendsLocationResponse()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Inventory\Types\LocationResponse', $this->obj);
    }
}
