<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace maiorADV\eBaySDK\Test\Merchandising\Types;

use maiorADV\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse;

class MerchandisingServiceItemResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new MerchandisingServiceItemResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse', $this->obj);
    }

    public function testExtendsBaseMerchandisingServiceResponse()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Merchandising\Types\BaseMerchandisingServiceResponse', $this->obj);
    }
}
