<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace maiorADV\eBaySDK\Test\MerchantData\Enums;

use maiorADV\eBaySDK\MerchantData\Enums\UnpaidItemCaseStatusTypeCodeType;

class UnpaidItemCaseStatusTypeCodeTypeTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new UnpaidItemCaseStatusTypeCodeType();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\MerchantData\Enums\UnpaidItemCaseStatusTypeCodeType', $this->obj);
    }
}
