<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace maiorADV\eBaySDK\HalfFinding\Services;

class HalfFindingService extends \maiorADV\eBaySDK\HalfFinding\Services\HalfFindingBaseService
{
    const API_VERSION = '1.2.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \maiorADV\eBaySDK\HalfFinding\Types\GetVersionRequest $request
     * @return \maiorADV\eBaySDK\HalfFinding\Types\GetVersionResponse
     */
    public function getVersion(\maiorADV\eBaySDK\HalfFinding\Types\GetVersionRequest $request)
    {
        return $this->getVersionAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\HalfFinding\Types\GetVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVersionAsync(\maiorADV\eBaySDK\HalfFinding\Types\GetVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getVersion',
            $request,
            '\maiorADV\eBaySDK\HalfFinding\Types\GetVersionResponse'
        );
    }

    /**
     * @param \maiorADV\eBaySDK\HalfFinding\Types\FindItemsRequest $request
     * @return \maiorADV\eBaySDK\HalfFinding\Types\FindItemsResponse
     */
    public function findHalfItems(\maiorADV\eBaySDK\HalfFinding\Types\FindItemsRequest $request)
    {
        return $this->findHalfItemsAsync($request)->wait();
    }

    /**
     * @param \maiorADV\eBaySDK\HalfFinding\Types\FindItemsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findHalfItemsAsync(\maiorADV\eBaySDK\HalfFinding\Types\FindItemsRequest $request)
    {
        return $this->callOperationAsync(
            'findHalfItems',
            $request,
            '\maiorADV\eBaySDK\HalfFinding\Types\FindItemsResponse'
        );
    }
}
