<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace maiorADV\eBaySDK\Test\Analytics\Types;

use maiorADV\eBaySDK\Analytics\Types\GetASpecificSellerProfileRestResponse;

class GetASpecificSellerProfileRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetASpecificSellerProfileRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Analytics\Types\GetASpecificSellerProfileRestResponse', $this->obj);
    }

    public function testExtendsStandardsProfile()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Analytics\Types\StandardsProfile', $this->obj);
    }
}
