<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace maiorADV\eBaySDK\Test\Account\Types;

use maiorADV\eBaySDK\Account\Types\GetAReturnPolicyByNameRestResponse;

class GetAReturnPolicyByNameRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetAReturnPolicyByNameRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Account\Types\GetAReturnPolicyByNameRestResponse', $this->obj);
    }

    public function testExtendsReturnPolicy()
    {
        $this->assertInstanceOf('\maiorADV\eBaySDK\Account\Types\ReturnPolicy', $this->obj);
    }
}
